[nginx-http-auth]
enabled = true
filter = nginx-http-auth
action = iptables[name=HTTP, port=80, protocol=tcp]
logpath = /var/log/nginx/error.log
maxretry = 5
bantime = 3600
findtime = 600

[nginx-limit-req]
enabled = true
filter = nginx-limit-req
action = iptables[name=ReqLimit, port=80, protocol=tcp]
logpath = /var/log/nginx/access.log
maxretry = 10
bantime = 1800
findtime = 600